import type { OrodhaData } from "./types";

const now = "2026-04-26T09:00:00.000Z";

const patient = (
  id: string,
  hospital_number: string,
  full_name: string,
  sex: OrodhaData["patients"][number]["sex"],
  date_of_birth: string,
  residence: string,
  caregiver_name: string,
  phone_primary: string,
  sha_status: OrodhaData["patients"][number]["sha_status"],
  notes: string | null = null,
): OrodhaData["patients"][number] => ({
  id,
  hospital_number,
  full_name,
  sex,
  date_of_birth,
  age_text: null,
  residence,
  caregiver_name,
  phone_primary,
  phone_secondary: null,
  sha_status,
  notes,
  created_at: now,
  updated_at: now,
});

const session = (
  id: string,
  session_date: string,
  max_cases = 3,
  overrides: Partial<OrodhaData["theatre_sessions"][number]> = {},
): OrodhaData["theatre_sessions"][number] => ({
  id,
  theatre_id: "th-main",
  session_date,
  session_name: "Paediatric Surgery List",
  max_cases,
  start_time: "08:00",
  end_time: "16:00",
  is_blocked: false,
  block_reason: null,
  notes: null,
  created_at: now,
  ...overrides,
});

const holiday = (id: string, session_date: string, block_reason: string) =>
  session(id, session_date, 3, {
    session_name: "Public Holiday",
    start_time: null,
    end_time: null,
    is_blocked: true,
    block_reason,
    notes: "Theatre closed for public holiday",
  });

const surgicalCase = (
  id: string,
  patient_id: string,
  specialty_id: string,
  procedure_name: string,
  priority: OrodhaData["surgical_cases"][number]["priority"],
  status: OrodhaData["surgical_cases"][number]["status"],
  overrides: Partial<OrodhaData["surgical_cases"][number]> = {},
): OrodhaData["surgical_cases"][number] => ({
  id,
  patient_id,
  specialty_id,
  procedure_id: null,
  procedure_name,
  diagnosis: null,
  indication: null,
  case_description: null,
  priority,
  status,
  estimated_duration_minutes: null,
  weight_kg: null,
  asa_class: "II",
  comorbidities: null,
  allergies: null,
  special_requirements: null,
  surgeon_id: null,
  anaesthetist_id: null,
  created_at: now,
  updated_at: now,
  ...overrides,
});

const preop = (
  id: string,
  case_id: string,
  overrides: Partial<OrodhaData["preop_assessments"][number]> = {},
): OrodhaData["preop_assessments"][number] => ({
  id,
  case_id,
  anaesthesia_status: "Pending",
  surgical_status: "Cleared",
  nursing_status: "Pending",
  consent_done: true,
  fasting_instructions_given: true,
  labs_required: false,
  labs_done: false,
  imaging_required: false,
  imaging_done: false,
  blood_required: false,
  blood_available: false,
  financial_clearance: true,
  preop_notes: null,
  assessed_at: null,
  updated_at: now,
  ...overrides,
});

const booking = (
  id: string,
  case_id: string,
  session_id: string,
  slot: number,
  booking_status: OrodhaData["bookings"][number]["booking_status"],
  overrides: Partial<OrodhaData["bookings"][number]> = {},
): OrodhaData["bookings"][number] => ({
  id,
  case_id,
  session_id,
  slot,
  booking_status,
  order_on_list: slot,
  postop_destination: "Ward",
  cancellation_reason: null,
  postponement_reason: null,
  outcome_notes: null,
  created_at: now,
  updated_at: now,
  ...overrides,
});

const patients: OrodhaData["patients"] = [
  patient("p1", "UMR0482156", "Amara Wanjiku Kamau", "Female", "2019-03-15", "Nairobi", "Mary Kamau", "0712345678", "Active"),
  patient("p2", "UMR0174803", "David Otieno Odhiambo", "Male", "2021-07-22", "Kisumu", "Peter Odhiambo", "0723456789", "Active"),
  patient("p3", "UMR0231256", "Faith Njeri Mwangi", "Female", "2018-11-08", "Thika", "Jane Mwangi", "0734567890", "Inactive", "Family prefers weekday theatre lists."),
  patient("p4", "UMR0395841", "Michael Kipchoge Langat", "Male", "2020-04-30", "Eldoret", "Daniel Langat", "0745678901", "Active"),
  patient("p5", "UMR0156234", "Grace Achieng Owino", "Female", "2022-01-14", "Mombasa", "Rose Owino", "0756789012", "Active"),
  patient("p6", "UMR0421789", "Samuel Mutua Kioko", "Male", "2017-09-03", "Machakos", "Mutua Kioko", "0767890123", "Inactive"),
  patient("p7", "UMR0308654", "Fatuma Hassan Ali", "Female", "2023-02-19", "Garissa", "Hassan Ali", "0778901234", "Active"),
  patient("p8", "UMR0267431", "Peter Njenga Kariuki", "Male", "2019-08-11", "Nyeri", "John Kariuki", "0789012345", "Active"),
  patient("p9", "UMR0512098", "Esther Wairimu Gachoki", "Female", "2020-12-05", "Nakuru", "Wairimu Gachoki", "0790123456", "Active"),
  patient("p10", "UMR0183742", "Ali Mohamed Abdullahi", "Male", "2018-05-27", "Wajir", "Mohamed Abdullahi", "0701234567", "Inactive"),
  patient("p11", "UMR0542801", "Leah Atieno Naliaka", "Female", "2019-10-09", "Bungoma", "Atieno Naliaka", "0718456123", "Active"),
  patient("p12", "UMR0563184", "Brian Omondi Oketch", "Male", "2021-02-03", "Siaya", "Janet Oketch", "0728345612", "Active"),
  patient("p13", "UMR0589902", "Zainab Noor Ibrahim", "Female", "2022-08-18", "Isiolo", "Noor Ibrahim", "0738345612", "Active"),
  patient("p14", "UMR0601245", "Kevin Kiptoo Cheruiyot", "Male", "2017-06-11", "Kericho", "Sarah Cheruiyot", "0748345612", "Active"),
  patient("p15", "UMR0617720", "Ruth Muthoni Kibe", "Female", "2020-02-20", "Kiambu", "Muthoni Kibe", "0758345612", "Active"),
  patient("p16", "UMR0634419", "Hannah Jepkosgei Tanui", "Female", "2018-01-29", "Uasin Gishu", "Jepkosgei Tanui", "0768345612", "Active"),
  patient("p17", "UMR0648103", "Elijah Mwangi Karanja", "Male", "2021-09-12", "Muranga", "Mwangi Karanja", "0778345612", "Active"),
  patient("p18", "UMR0672150", "Asha Wanjiru Ndegwa", "Female", "2023-03-07", "Naivasha", "Wanjiru Ndegwa", "0788345612", "Active"),
];

const theatre_sessions: OrodhaData["theatre_sessions"] = [
  holiday("ts-2026-01-01", "2026-01-01", "New Year's Day"),
  holiday("ts-2026-03-20", "2026-03-20", "Idd ul-Fitr"),
  holiday("ts-2026-04-03", "2026-04-03", "Good Friday"),
  holiday("ts-2026-04-06", "2026-04-06", "Easter Monday"),
  session("ts-2026-04-14", "2026-04-14", 3, { notes: "Completed full list" }),
  session("ts-2026-04-17", "2026-04-17", 3, { notes: "Mixed outcomes day" }),
  session("ts-2026-04-21", "2026-04-21", 3, { notes: "One postponed, one completed" }),
  session("ts-2026-04-24", "2026-04-24", 3, { notes: "Completed day list" }),
  session("ts-2026-04-28", "2026-04-28", 3, { notes: "Upcoming partial list" }),
  session("ts-2026-04-29", "2026-04-29", 3, { notes: "Upcoming full list" }),
  holiday("ts-2026-05-01", "2026-05-01", "Labour Day"),
  session("ts-2026-05-05", "2026-05-05", 4, { notes: "Four-slot overflow list" }),
  session("ts-2026-05-12", "2026-05-12", 3),
  session("ts-2026-05-19", "2026-05-19", 3),
  session("ts-2026-05-26", "2026-05-26", 3),
  holiday("ts-2026-06-01", "2026-06-01", "Madaraka Day"),
  session("ts-2026-06-04", "2026-06-04", 3),
  session("ts-2026-06-16", "2026-06-16", 3, { notes: "Booked to capacity" }),
  session("ts-2026-06-23", "2026-06-23", 3),
  session("ts-2026-07-07", "2026-07-07", 3),
  session("ts-2026-08-11", "2026-08-11", 3),
  session("ts-2026-09-08", "2026-09-08", 3),
  holiday("ts-2026-10-10", "2026-10-10", "Mazingira Day"),
  holiday("ts-2026-10-20", "2026-10-20", "Mashujaa Day"),
  session("ts-2026-11-03", "2026-11-03", 3),
  holiday("ts-2026-12-12", "2026-12-12", "Jamhuri Day"),
  holiday("ts-2026-12-25", "2026-12-25", "Christmas Day"),
  holiday("ts-2026-12-26", "2026-12-26", "Boxing Day"),
];

const surgical_cases: OrodhaData["surgical_cases"] = [
  surgicalCase("c1", "p5", "sp-urology", "Pyeloplasty", "Elective", "Booked", { diagnosis: "UPJO", indication: "Progressive hydronephrosis", estimated_duration_minutes: 150, weight_kg: 13.4, asa_class: "II", special_requirements: "MAG3 renogram reviewed" }),
  surgicalCase("c2", "p2", "sp-colorectal", "Pull-through Procedure", "Elective", "Booked", { diagnosis: "Hirschsprung disease", indication: "Definitive repair", estimated_duration_minutes: 180, weight_kg: 16.2, special_requirements: "Biopsy confirmed aganglionosis to sigmoid" }),
  surgicalCase("c3", "p3", "sp-hernia", "Bilateral Inguinal Hernia Repair", "Elective", "Awaiting booking", { diagnosis: "Bilateral inguinal hernias", indication: "Reducible hernias", estimated_duration_minutes: 90, weight_kg: 19.1, asa_class: "I" }),
  surgicalCase("c4", "p1", "sp-hpb", "Hepatoportoenterostomy", "Urgent", "Booked", { diagnosis: "Biliary atresia", indication: "Persistent cholestasis", estimated_duration_minutes: 240, weight_kg: 21.6, asa_class: "III", comorbidities: "Cholestasis", special_requirements: "ICU bed required" }),
  surgicalCase("c5", "p4", "sp-minor", "Circumcision", "Elective", "Done", { diagnosis: "Phimosis", indication: "Recurrent balanitis", estimated_duration_minutes: 45, weight_kg: 18.8, asa_class: "I" }),
  surgicalCase("c6", "p2", "sp-colorectal", "Colostomy Takedown", "Elective", "Done", { diagnosis: "Anorectal malformation", indication: "Stoma closure", estimated_duration_minutes: 120, weight_kg: 16.2 }),
  surgicalCase("c7", "p5", "sp-hernia", "Bilateral Orchidopexy", "Elective", "Done", { diagnosis: "Bilateral undescended testes", indication: "Definitive fixation", estimated_duration_minutes: 90, weight_kg: 13.4, asa_class: "I" }),
  surgicalCase("c8", "p10", "sp-hpb", "Hepatoportoenterostomy (Kasai)", "Urgent", "Done", { diagnosis: "Biliary atresia", indication: "Early biliary drainage", estimated_duration_minutes: 240, weight_kg: 18.1, asa_class: "III", special_requirements: "ICU booked" }),
  surgicalCase("c9", "p7", "sp-oncology", "Retroperitoneal Lymph Node Dissection", "Urgent", "Booked", { diagnosis: "Germ cell tumour", indication: "Residual mass", estimated_duration_minutes: 210, weight_kg: 10.2, asa_class: "III", special_requirements: "Blood available" }),
  surgicalCase("c10", "p8", "sp-urology", "Orchidopexy", "Elective", "Booked", { diagnosis: "Undescended testis", indication: "Elective fixation", estimated_duration_minutes: 80, weight_kg: 20.2, asa_class: "I" }),
  surgicalCase("c11", "p9", "sp-urology", "Ureteric Reimplantation", "Elective", "Cancelled", { diagnosis: "VUR", indication: "Breakthrough infections", estimated_duration_minutes: 150, weight_kg: 17.8 }),
  surgicalCase("c12", "p6", "sp-other", "Appendicostomy Revision", "Semi-urgent", "Booked", { diagnosis: "Stomal stenosis", indication: "Revision for washout access", estimated_duration_minutes: 120, weight_kg: 24.1, special_requirements: "Stoma therapist review" }),
  surgicalCase("c13", "p4", "sp-urology", "Hypospadias Repair", "Elective", "Done", { diagnosis: "Distal hypospadias", indication: "Planned repair", estimated_duration_minutes: 140, weight_kg: 18.8 }),
  surgicalCase("c14", "p1", "sp-urology", "Bladder Neck Reconstruction", "Elective", "Booked", { diagnosis: "Bladder outlet dysfunction", indication: "Continence pathway", estimated_duration_minutes: 210, weight_kg: 21.6 }),
  surgicalCase("c15", "p3", "sp-urology", "Nephrectomy", "Elective", "Cancelled", { diagnosis: "Non-functioning kidney", indication: "Symptomatic hydronephrosis", estimated_duration_minutes: 170, weight_kg: 19.1 }),
  surgicalCase("c16", "p11", "sp-uppergi", "Choledochal Cyst Excision", "Urgent", "Booked", { diagnosis: "Choledochal cyst", indication: "Progressive cholangitis", estimated_duration_minutes: 220, weight_kg: 20.1, asa_class: "III" }),
  surgicalCase("c17", "p12", "sp-colorectal", "Anal Dilatation", "Elective", "Done", { diagnosis: "Post-operative stricture", indication: "Planned dilatation", estimated_duration_minutes: 50, weight_kg: 12.5, asa_class: "I" }),
  surgicalCase("c18", "p13", "sp-uppergi", "Ladd Procedure", "Urgent", "Booked", { diagnosis: "Malrotation", indication: "Intermittent volvulus symptoms", estimated_duration_minutes: 160, weight_kg: 11.2, asa_class: "II" }),
  surgicalCase("c19", "p14", "sp-oncology", "Wilms Tumour Biopsy", "Urgent", "Booked", { diagnosis: "Left renal mass", indication: "Tissue diagnosis", estimated_duration_minutes: 90, weight_kg: 28.3, asa_class: "II" }),
  surgicalCase("c20", "p15", "sp-other", "Port Insertion", "Elective", "Postponed", { diagnosis: "Need for chemotherapy access", indication: "Long-term venous access", estimated_duration_minutes: 60, weight_kg: 15.6, asa_class: "II" }),
  surgicalCase("c21", "p16", "sp-urology", "Urethroplasty", "Elective", "Booked", { diagnosis: "Urethral stricture", indication: "Definitive repair", estimated_duration_minutes: 160, weight_kg: 22.0 }),
  surgicalCase("c22", "p17", "sp-colorectal", "Ileostomy Closure", "Elective", "Booked", { diagnosis: "Protective ileostomy", indication: "Restoration of continuity", estimated_duration_minutes: 130, weight_kg: 13.1 }),
  surgicalCase("c23", "p18", "sp-oncology", "Excision Biopsy", "Semi-urgent", "Booked", { diagnosis: "Abdominal wall mass", indication: "Histology", estimated_duration_minutes: 70, weight_kg: 9.8 }),
  surgicalCase("c24", "p7", "sp-urology", "Ureteric Reimplantation", "Elective", "Booked", { diagnosis: "Ectopic ureter", indication: "Recurrent infections", estimated_duration_minutes: 160, weight_kg: 10.2 }),
  surgicalCase("c25", "p9", "sp-minor", "Central Line Insertion", "Elective", "Booked", { diagnosis: "Need for prolonged antibiotics", indication: "Long line placement", estimated_duration_minutes: 45, weight_kg: 17.8, asa_class: "I" }),
  surgicalCase("c26", "p11", "sp-uppergi", "Oesophageal Dilatation", "Semi-urgent", "Booked", { diagnosis: "Anastomotic stricture", indication: "Dysphagia", estimated_duration_minutes: 60, weight_kg: 20.1 }),
  surgicalCase("c27", "p16", "sp-urology", "Pyeloplasty", "Elective", "Booked", { diagnosis: "UPJO", indication: "Persistent pain and dilatation", estimated_duration_minutes: 150, weight_kg: 22.0 }),
  surgicalCase("c28", "p17", "sp-colorectal", "Pull-through Revision", "Semi-urgent", "Booked", { diagnosis: "Residual cuff issues", indication: "Ongoing obstructive symptoms", estimated_duration_minutes: 190, weight_kg: 13.1, asa_class: "III" }),
  surgicalCase("c29", "p18", "sp-other", "Hydrocele Repair", "Elective", "Booked", { diagnosis: "Communicating hydrocele", indication: "Persistent symptoms", estimated_duration_minutes: 55, weight_kg: 9.8, asa_class: "I" }),
  surgicalCase("c30", "p14", "sp-oncology", "Port Removal", "Elective", "Booked", { diagnosis: "Completed treatment", indication: "Device no longer required", estimated_duration_minutes: 40, weight_kg: 28.3, asa_class: "I" }),
  surgicalCase("c31", "p12", "sp-other", "Patent Urachus Excision", "Elective", "Booked", { diagnosis: "Patent urachus", indication: "Persistent discharge", estimated_duration_minutes: 85, weight_kg: 12.5, asa_class: "I" }),
];

const preop_assessments: OrodhaData["preop_assessments"] = [
  preop("pa1", "c1", { anaesthesia_status: "Cleared", nursing_status: "Pending", labs_required: true, labs_done: true, imaging_required: true, imaging_done: true, preop_notes: "MAG3 renogram done. Parent counselled.", assessed_at: now }),
  preop("pa2", "c2", { anaesthesia_status: "Pending", labs_required: true, labs_done: false, blood_required: true, blood_available: false, preop_notes: "Bowel prep plan to confirm." }),
  preop("pa3", "c3", { anaesthesia_status: "Not assessed", surgical_status: "Pending", nursing_status: "Not assessed", consent_done: false, fasting_instructions_given: false, financial_clearance: false }),
  preop("pa4", "c4", { anaesthesia_status: "Not cleared", labs_required: true, labs_done: true, imaging_required: true, imaging_done: true, blood_required: true, blood_available: false, financial_clearance: false, preop_notes: "Original date postponed pending ICU and blood availability.", assessed_at: now }),
  preop("pa5", "c5", { anaesthesia_status: "Cleared", surgical_status: "Cleared", nursing_status: "Cleared", preop_notes: "Completed uneventfully.", assessed_at: now }),
  preop("pa6", "c6", { anaesthesia_status: "Cleared", surgical_status: "Cleared", nursing_status: "Cleared", labs_required: true, labs_done: true, preop_notes: "Bowel prep completed.", assessed_at: now }),
  preop("pa7", "c7", { anaesthesia_status: "Cleared", surgical_status: "Cleared", nursing_status: "Cleared", assessed_at: now }),
  preop("pa8", "c8", { anaesthesia_status: "Cleared", surgical_status: "Cleared", nursing_status: "Cleared", labs_required: true, labs_done: true, imaging_required: true, imaging_done: true, blood_required: true, blood_available: true, preop_notes: "ICU bed reserved.", assessed_at: now }),
  preop("pa9", "c9", { labs_required: true, labs_done: true, imaging_required: true, imaging_done: true, blood_required: true, blood_available: true, preop_notes: "CT reviewed in MDT.", assessed_at: now }),
  preop("pa10", "c10", { consent_done: false, fasting_instructions_given: false }),
  preop("pa11", "c11", { anaesthesia_status: "Pending", preop_notes: "Cancelled due to intercurrent URTI." }),
  preop("pa12", "c12", { labs_required: true, labs_done: true, preop_notes: "Rebooked after anaesthesia review.", assessed_at: now }),
  preop("pa13", "c13", { anaesthesia_status: "Cleared", surgical_status: "Cleared", nursing_status: "Cleared", assessed_at: now }),
  preop("pa14", "c14", { labs_required: true, labs_done: true, blood_required: true, blood_available: true, preop_notes: "Urodynamics filed.", assessed_at: now }),
  preop("pa15", "c15", { financial_clearance: false, preop_notes: "Family requested deferment." }),
  preop("pa16", "c16", { labs_required: true, labs_done: true, imaging_required: true, imaging_done: true, blood_required: true, blood_available: true, preop_notes: "MRCP images uploaded.", assessed_at: now }),
  preop("pa17", "c17", { anaesthesia_status: "Cleared", surgical_status: "Cleared", nursing_status: "Cleared", assessed_at: now }),
  preop("pa18", "c18", { labs_required: true, labs_done: true, preop_notes: "Intermittent bilious vomiting. Prioritise if symptoms worsen." }),
  preop("pa19", "c19", { imaging_required: true, imaging_done: true, labs_required: true, labs_done: true, preop_notes: "Cross-match available.", assessed_at: now }),
  preop("pa20", "c20", { preop_notes: "Family did not attend for original date.", financial_clearance: false }),
  preop("pa21", "c21", { labs_required: true, labs_done: true, preop_notes: "Urethrogram reviewed.", assessed_at: now }),
  preop("pa22", "c22", { labs_required: true, labs_done: true, preop_notes: "Stoma output reducing appropriately.", assessed_at: now }),
  preop("pa23", "c23", { preop_notes: "Short case. Day-case review acceptable.", assessed_at: now }),
  preop("pa24", "c24", { labs_required: true, labs_done: true, preop_notes: "DMSA reviewed.", assessed_at: now }),
  preop("pa25", "c25", { preop_notes: "Ward antibiotics ongoing.", assessed_at: now }),
  preop("pa26", "c26", { preop_notes: "Swallow study uploaded.", assessed_at: now }),
  preop("pa27", "c27", { labs_required: true, labs_done: true, imaging_required: true, imaging_done: true, preop_notes: "Renal split function stable.", assessed_at: now }),
  preop("pa28", "c28", { labs_required: true, labs_done: true, preop_notes: "To be discussed in morning brief.", assessed_at: now }),
  preop("pa29", "c29", { assessed_at: now }),
  preop("pa30", "c30", { assessed_at: now }),
  preop("pa31", "c31", { labs_required: true, labs_done: true, assessed_at: now }),
];

const bookings: OrodhaData["bookings"] = [
  booking("b6", "c6", "ts-2026-04-14", 1, "Done", { postop_destination: "Ward", outcome_notes: "Completed." }),
  booking("b7", "c7", "ts-2026-04-14", 2, "Done", { postop_destination: "Day case", outcome_notes: "Completed." }),
  booking("b8", "c8", "ts-2026-04-14", 3, "Done", { postop_destination: "ICU", outcome_notes: "Completed." }),
  booking("b11", "c11", "ts-2026-04-17", 1, "Cancelled", { cancellation_reason: "Upper respiratory tract infection", postop_destination: null }),
  booking("b18", "c17", "ts-2026-04-17", 2, "Done", { postop_destination: "Day case", outcome_notes: "Completed." }),
  booking("b20", "c20", "ts-2026-04-17", 3, "No-show", { postop_destination: null, outcome_notes: "Family did not arrive for admission." }),
  booking("b14", "c13", "ts-2026-04-21", 1, "Done", { postop_destination: "Ward", outcome_notes: "Completed." }),
  booking("b31", "c4", "ts-2026-04-21", 2, "Postponed", { postop_destination: "ICU", postponement_reason: "No ICU bed available" }),
  booking("b5", "c5", "ts-2026-04-24", 1, "Done", { postop_destination: "Day case", outcome_notes: "Discharged stable." }),
  booking("b1", "c1", "ts-2026-04-28", 1, "Booked", { postop_destination: "Ward" }),
  booking("b2", "c2", "ts-2026-04-29", 1, "Booked", { postop_destination: "HDU" }),
  booking("b33", "c21", "ts-2026-04-29", 2, "Booked", { postop_destination: "Ward" }),
  booking("b34", "c24", "ts-2026-04-29", 3, "Booked", { postop_destination: "Ward" }),
  booking("b4", "c4", "ts-2026-05-05", 1, "Booked", { postop_destination: "ICU" }),
  booking("b22", "c23", "ts-2026-05-05", 2, "Booked", { postop_destination: "Ward" }),
  booking("b23", "c25", "ts-2026-05-05", 3, "Booked", { postop_destination: "Ward" }),
  booking("b24", "c26", "ts-2026-05-05", 4, "Booked", { postop_destination: "Ward" }),
  booking("b15", "c14", "ts-2026-05-12", 1, "Booked", { postop_destination: "Ward" }),
  booking("b10", "c10", "ts-2026-05-12", 2, "Booked", { postop_destination: "Ward" }),
  booking("b12", "c12", "ts-2026-05-19", 2, "Postponed", { postop_destination: "Ward", postponement_reason: "Anaesthesia review incomplete" }),
  booking("b35", "c29", "ts-2026-05-26", 1, "Booked", { postop_destination: "Day case" }),
  booking("b16", "c15", "ts-2026-05-26", 3, "Cancelled", { postop_destination: null, cancellation_reason: "Family requested deferment" }),
  booking("b9", "c9", "ts-2026-06-04", 3, "Booked", { postop_destination: "HDU" }),
  booking("b17", "c16", "ts-2026-06-16", 1, "Booked", { postop_destination: "HDU" }),
  booking("b25", "c22", "ts-2026-06-16", 2, "Booked", { postop_destination: "Ward" }),
  booking("b26", "c27", "ts-2026-06-16", 3, "Booked", { postop_destination: "Ward" }),
  booking("b27", "c28", "ts-2026-06-23", 1, "Booked", { postop_destination: "Ward" }),
  booking("b13", "c12", "ts-2026-06-23", 2, "Booked", { postop_destination: "Ward" }),
  booking("b19", "c18", "ts-2026-07-07", 1, "Booked", { postop_destination: "Ward" }),
  booking("b28", "c30", "ts-2026-08-11", 2, "Booked", { postop_destination: "Day case" }),
  booking("b21", "c19", "ts-2026-09-08", 1, "Booked", { postop_destination: "Ward" }),
  booking("b29", "c31", "ts-2026-11-03", 1, "Booked", { postop_destination: "Ward" }),
];

export const demoData: OrodhaData = {
  specialties: [
    { id: "sp-urology", name: "Urological", active: true },
    { id: "sp-colorectal", name: "Colorectal", active: true },
    { id: "sp-hernia", name: "Hernias & Testis", active: true },
    { id: "sp-uppergi", name: "Upper GI", active: true },
    { id: "sp-hpb", name: "Hepatobiliary", active: true },
    { id: "sp-minor", name: "Minor Procedures", active: true },
    { id: "sp-oncology", name: "Oncological", active: true },
    { id: "sp-other", name: "Other", active: true },
  ],
  procedures: [
    { id: "pr-pyeloplasty", specialty_id: "sp-urology", name: "Pyeloplasty", default_duration_minutes: 150, active: true },
    { id: "pr-pullthrough", specialty_id: "sp-colorectal", name: "Pull-through Procedure", default_duration_minutes: 180, active: true },
    { id: "pr-hernia", specialty_id: "sp-hernia", name: "Inguinal Hernia Repair", default_duration_minutes: 75, active: true },
    { id: "pr-kasai", specialty_id: "sp-hpb", name: "Hepatoportoenterostomy", default_duration_minutes: 240, active: true },
    { id: "pr-nephrectomy", specialty_id: "sp-urology", name: "Nephrectomy", default_duration_minutes: 170, active: true },
    { id: "pr-ureteric", specialty_id: "sp-urology", name: "Ureteric Reimplantation", default_duration_minutes: 160, active: true },
    { id: "pr-hypospadias", specialty_id: "sp-urology", name: "Hypospadias Repair", default_duration_minutes: 140, active: true },
    { id: "pr-biopsy", specialty_id: "sp-oncology", name: "Excision Biopsy", default_duration_minutes: 70, active: true },
  ],
  theatres: [
    { id: "th-main", name: "Main Paediatric Theatre", location: "Main theatre block", active: true },
    { id: "th-day", name: "Day Surgery Theatre", location: "Ambulatory wing", active: true },
  ],
  theatre_sessions,
  patients,
  surgical_cases,
  preop_assessments,
  bookings,
  case_notes: [
    { id: "n1", case_id: "c4", note_type: "Booking", note: "Original booking postponed; rebooked without losing history.", created_at: now },
    { id: "n2", case_id: "c11", note_type: "Cancellation", note: "Cancelled after URI symptoms on pre-op review.", created_at: now },
    { id: "n3", case_id: "c12", note_type: "Theatre", note: "Rebooked to June list after anaesthesia review completed.", created_at: now },
    { id: "n4", case_id: "c20", note_type: "Attendance", note: "Marked no-show; nurse to contact family for re-listing.", created_at: now },
  ],
};

export const cancellationReasons = [
  "Patient unfit for surgery",
  "Upper respiratory tract infection",
  "No-show / did not attend",
  "Fasting failure",
  "Theatre overrun",
  "Equipment unavailable",
  "Surgeon unavailable",
  "Other",
];
